name: "update flake inputs"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@v27
        with:
          token: ${{ secrets.NIX_FLAKE_UPDATE_PAT }}
          pr-title: "Update Nix flake inputs"
          pr-labels: |
            dependencies
            automated
